hosts:
    localhost:
        env_home: $HOME/mordor
deployments:
    sample_beta:
        name: sample
        stage: beta
        home_dir: samples/simple/src
        deploy_to:
            - localhost
        config:
            foo.json: copy
